// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'category',
          label: 'Module 1: The Foundation',
          link: {
            type: 'generated-index',
          },
          items: [{type: 'autogenerated', dirName: 'module-1'}],
        },
        {
          type: 'category',
          label: 'Module 2: ROS 2',
          link: {
            type: 'generated-index',
          },
          items: [{type: 'autogenerated', dirName: 'module-2'}],
        },
        {
          type: 'category',
          label: 'Module 3: Gazebo',
          link: {
            type: 'generated-index',
          },
          items: [{type: 'autogenerated', dirName: 'module-3'}],
        },
        {
          type: 'category',
          label: 'Module 4: NVIDIA Isaac',
          link: {
            type: 'generated-index',
          },
          items: [{type: 'autogenerated', dirName: 'module-4'}],
        },
        {
          type: 'category',
          label: 'Module 5: Humanoid Development',
          link: {
            type: 'generated-index',
          },
          items: [{type: 'autogenerated', dirName: 'module-5'}],
        },
        {
          type: 'category',
          label: 'Module 6: Conversational Robotics/Capstone',
          link: {
            type: 'generated-index',
          },
          items: [{type: 'autogenerated', dirName: 'module-6'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'hardware-requirements',
        'glossary',
        'assessment-guidelines',
        'prerequisites-setup',
        'additional-resources',
      ],
    },
  ],
};

export default sidebars;
